name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        # FTP server name (you may need to specify a port)
        FTP_SERVER: andrus.itmajakas.ee
        # FTP account username
        FTP_USERNAME: andrus.andrus.itmajakas.ee
        # FTP account password
        FTP_PASSWORD: ${{ secrets.FTP_PAROOL }}
        # The port used to connect to server
        port: 21 
        # The remote folder to copy to, deafults to root FTP folder (I recommend you configure this on your server side instead of here)
        remote_dir: /ta18projekt

