name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        # FTP server name (you may need to specify a port)
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        # FTP account username
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        # FTP account password
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        # The remote folder to copy to, deafults to root FTP folder (I recommend you configure this on your server side instead of here)
        REMOTE_DIR: ta18projekt
        #        ARGS: --delete

